### ISSUE TITLE
Sample description is a generic placeholder text

### ISSUE THREAD

**Issue by al-broco** [googlesamples/android-RepeatingAlarm#1]
The sample description has a placeholder text, it reads: "Introductory text that explains what the sample is intended to demonstrate. Edit in template-params.xml.".

This is shown both on github and in the "import sample" dialog in Android Studio.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
